name: build

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Test iOS
      run: |
        xcodebuild build -scheme DigiMeSDK -destination "platform=iOS Simulator,name=iPhone 14" | xcpretty